name: Format Code

on: [pull_request]

jobs:
  cxx-format-check:
    name: C++ Format Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clang Format
      uses: RafikFarhad/clang-format-github-action@v3
      with:
        sources: src/**/*.h,src/**/*.cpp
        style: file